//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pro100Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat_useres
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ChatID { get; set; }
    
        public virtual Chat Chat { get; set; }
        public virtual Profiless Profiless { get; set; }
    }
}
