//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pro100Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message_File
    {
        public int ID { get; set; }
        public Nullable<int> MessageID { get; set; }
        public Nullable<int> FileID { get; set; }
    
        public virtual Message Message { get; set; }
    }
}
