//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pro100Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_Bots
    {
        public int BotID { get; set; }
        public string name { get; set; }
        public string token { get; set; }
        public Nullable<int> Bot_type_ID { get; set; }
        public bool is_work { get; set; }
    
        public virtual TypeOfBots TypeOfBots { get; set; }
    }
}
