//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pro100Server.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class u436263_robotEntities2 : DbContext
    {
        public u436263_robotEntities2()
            : base("name=u436263_robotEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Chat> Chat { get; set; }
        public virtual DbSet<Chat_useres> Chat_useres { get; set; }
        public virtual DbSet<Genders> Genders { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<Message_File> Message_File { get; set; }
        public virtual DbSet<Message_to_user> Message_to_user { get; set; }
        public virtual DbSet<MM_Bots> MM_Bots { get; set; }
        public virtual DbSet<Profiless> Profiless { get; set; }
        public virtual DbSet<TypeOfBots> TypeOfBots { get; set; }
    }
}
