//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pro100Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profiless
    {
        public int ID { get; set; }
        public Nullable<int> Bot_type_ID { get; set; }
        public string UserID { get; set; }
        public string Username { get; set; }
        public string Name { get; set; }
        public string Lastname { get; set; }
        public string Surname { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Genders Genders { get; set; }
        public virtual TypeOfBots TypeOfBots { get; set; }
    }
}
